#!/usr/bin/python3
import toml

from model.cluster import Creator, Cluster, Clusters
from model.project import Project, Projects

clusters_toml = toml.load("./cfg/clusters.toml")

clusters = []
for name, cluster_info in clusters_toml.items():
    cluster = Cluster(
        name,
        cluster_info.get('description', ''),
        [Creator(creator) for creator in cluster_info['creators']],
    )
    clusters.append(cluster)
CLUSTERS = Clusters(clusters)

PROJECTS = Projects([
    Project(
        name='disneydreamlightvalley_30d',
        description='Popular Disney Dreamlight Valley clips!',
        title='Disney Dreamlight Valley',
        playlist_title='Disney Dreamlight Valley',
        game_ids=['1515862749'],
        days=30,
        n_per_month=1,
        is_active=True,
    ),
    Project(
        name='thequarry_30d',
        description='Popular The Quarry twitch clips!',
        title='The Quarry',
        playlist_title='The Quarry',
        game_ids=['1937599489'],
        days=30,
        n_per_month=2,
        is_active=False,
    ),
    Project(
        name='overwatch2_30d',
        description='Popular Overwatch 2 twitch clips!',
        title='Overwatch 2',
        playlist_title='Overwatch 2',
        game_ids=['515025'],
        days=30,
        n_per_month=2,
        is_active=True,
    ),
    Project(
        name='apex_30d',
        description='Popular Apex Legends twitch clips past 30 days!',
        title='Apex Legends',
        playlist_title='Apex legends',
        game_ids=['511224'],
        days=30,
        n_per_month=1,
    ),
    Project(
        name='csgo_30d',
        description='Popular Counter-Strike Global Offensive twitch clips past 30 days!',
        title='CSGO',
        playlist_title='Counter-Strike: Global Offensive',
        game_ids=['32399'],
        days=30,
        n_per_month=1,
    ),
    Project(
        name='fortnite_30d',
        description='Popular Fortnite twitch clips past 30 days!',
        title='Fortnite',
        playlist_title='Fortnite',
        game_ids=['33214'],
        days=50,
        n_per_month=1,
    ),
    Project(
        name='gta5_30d',
        description='Popular Grand Theft Auto V twitch clips past 30 days!',
        title='GTA V',
        playlist_title='GTA V',
        game_ids=['32982'],
        days=30,
        n_per_month=1,
    ),
    Project(
        name='league_30d',
        description='Popular League of Legends twitch clips past 30 days!',
        title='League of Legends',
        playlist_title='League of Legends',
        game_ids=['21779'],
        days=30,
        n_per_month=2,
    ),
    Project(
        name='league_7d',
        title='League of Legends',
        playlist_title='League of Legends',
        description='popular league of legends clips past 7 days',
        game_ids=['21779'],
        days=7,
        duration=300,
        n_per_month=4,
    ),
    Project(
        name='valorant_14d',
        title='Valorant',
        playlist_title='Valorant',
        description='valorant clips',
        game_ids=['516575'],
        duration=180,
        days=14,
        n_per_month=2,
    ),
    Project(
        name='valorant_30d',
        title='Valorant',
        playlist_title='Valorant',
        description='valorant clips',
        game_ids=['516575'],
        days=30,
        n_per_month=1,
    ),
    Project(
        name='pools_30d',
        title='Pools, Hot Tubs and Beaches',
        playlist_title='Pools, Hot Tubs and Beaches',
        description='Pools, Hot Tubs and Beaches',
        game_ids=['116747788'],
        days=30,
        n_per_month=2,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='asmr_30d',
        title='ASMR',
        playlist_title='ASMR',
        description='Popular Twitch ASMR clips',
        game_ids=['509659'],
        days=30,
        n_per_month=2,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='asmr_short',
        title='ASMR',
        playlist_title='ASMR',
        description='Popular Twitch ASMR clips',
        game_ids=['509659'],
        days=10,
        n_per_month=3,
        single=True,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='just_chatting_30d',
        title='Just Chatting',
        playlist_title='Just Chatting',
        description='Popular Twitch Just Chatting clips',
        game_ids=['509658'],
        days=30,
        n_per_month=2,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='just_chatting_7d',
        title='Just Chatting',
        playlist_title='Just Chatting',
        description='Popular Twitch Just Chatting clips',
        game_ids=['509658'],
        days=7,
        n_per_month=3,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='pools_single',
        title='Pools, Hot Tubs and Beaches',
        playlist_title='Pools, Hot Tubs and Beaches',
        description='Pools, Hot Tubs and Beaches',
        game_ids=['116747788'],
        clusters=[
            ('camgirls'),
            ('asians'),
        ],
        single=True,
        days=7,
        duration=180,
        n_per_month=4,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='pools_short',
        title='Pools, Hot Tubs and Beaches',
        playlist_title='Pools, Hot Tubs and Beaches',
        description='Pools, Hot Tubs and Beaches',
        game_ids=['116747788'],
        clusters=[
            ('camgirls'),
            ('asians'),
        ],
        days=15,
        duration=180,
        n_per_month=2,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='vtubers_7d',
        title='VTubers',
        playlist_title='VTubers',
        description='popular vtuber clips past 7 days',
        clusters=[('vtubers')],
        days=7,
        n_per_month=4,
    ),
    Project(
        name='vtubers_30d',
        title='VTubers',
        playlist_title='VTubers',
        description='popular vtuber clips',
        clusters=[('vtubers')],
        days=30,
        n_per_month=2,
    ),
    Project(
        name='vtubers_short',
        title='VTuber',
        playlist_title='VTubers',
        description='Popular Twitch VTuber clip',
        clusters=[('vtubers')],
        single=True,
        days=7,
        n_per_month=4,
    ),
    Project(
        name='asians_30d',
        title='AZN',
        playlist_title='Pools, Hot Tubs and Beaches',
        description='popular clips form r/twitchasians',
        clusters=[('asians')],
        days=30,
        n_per_month=1,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='orange_30d',
        title='NA Orange',
        description='NA Orange league',
        clusters=[('orange')],
        days=30,
        n_per_month=2,
    ),
    Project(
        name='camgirls_30d',
        title='UHH',
        playlist_title='Pools, Hot Tubs and Beaches',
        description='popular twitch clips',
        clusters=[('camgirls')],
        game_ids=['116747788'],
        days=30,
        n_per_month=2,
        youtube_category_id = "24", # Gaming 20,  Entertainment 24, People Blogs 22,
    ),
    Project(
        name='napopular_30d',
        title='NA',
        description='NA popular',
        clusters=[('napopularpinkone'), ('napopularpinktwo')],
        days=30,
        n_per_month=4,
    ),
        Project(
        name='napopularcyan_30d',
        title='Shooters NA',
        description='Popular Twitch clips from NA',
        clusters=['napopularcyan'],
        days=30,
        n_per_month=4,
    ),
])
