## Twitch_atlas input.toml generated below
[lightgreen]
algo = 'color'
max = 50
creators = [
    'Albralelie',
    'Almxnd',
    'Apryze',
    'bateson87',
    'Blazt',
    'cloakzy',
    'daltoosh',
    'Destroy',
    'Dezignful',
    'DiazBiffle',
    'Diegosaurs',
    'DougisRaw',
    'egosaurs',
    'FabrizioRomano',
    'Faide',
    'fifakillvizualz',
    'fuji720x',
    'GuhRL',
    'IceManIsaac',
    'iiTzTimmy',
    'its_iron',
    'jarnoopmeer',
    'kurt0411',
    'LuluLuvely',
    'Mande',
    'Mendo',
    'Merk',
    'methodz',
    'MuTeX',
    'Natarsha',
    'Naughty',
    'NiceWigg',
    'NICKMERCS',
    'Ninja',
    'Nokokopuffs',
    'Pieface23',
    'scump',
    'ShivFPS',
    'Snip3down',
    'stormen',
    'Swagg',
    'taxi2g',
    'TeePee',
    'Tfue',
    'TheDanDangler',
    'TrueGeordie',
    'TSM_ImperialHal',
    'wagnificent',
    'Zoomaa',
]

[purple]
algo = 'color'
max = 50
creators = [
    'AbdulHD',
    'AnthonyZ',
    'Ash_on_LoL',
    'Autumn',
    'bananabrea',
    'BazzaGazza',
    'Biotoxz_',
    'Blaustoise',
    'buddha',
    'CathFawr',
    'Chap',
    'Crystalst',
    'curvyelephant',
    'Deansocool',
    'Denis3D',
    'freyzplayz',
    'GrandPOObear',
    'GreenishMonkey',
    'Hotted89',
    'HutchMF',
    'iddqd',
    'ikittyyyy',
    'ItsSammyP',
    'Jonthebroski',
    'Kate',
    'Kiva',
    'Kiwo',
    'koil',
    'Kongfue',
    'Kyle',
    'LAGTVMaximusBlack',
    'LunaOni',
    'Lysium',
    'MattRP',
    'Ming',
    'neutreN',
    'PENTA',
    'Ramee',
    'RatedEpicz',
    'Ray__C',
    'Roxmiral',
    'Shotz',
    'SilentSentry',
    'Timmac',
    'UberHaxorNova',
    'uhSnow',
    'Whippy',
    'Ziggy',
]

[cyan]
algo = 'color'
max = 80
creators = [
    'A_Seagull',
    'Alkaizerx',
    'Anthony_Kongphan',
    'AquaFPS',
    'Asmongold',
    'AvoidingThePuddle',
    'BarbarousKing',
    'Bawkbasoup',
    'BobRoss',
    'BoxyFresh',
    'BurkeBlack',
    'Calebhart42',
    'cdewx',
    'CDNThe3rd',
    'chocoTaco',
    'CohhCarnage',
    'CriticalRole',
    'CuteDog_',
    'DatModz',
    'Datto',
    'Day9tv',
    'Deadlyslob',
    'Distortion2',
    'DizzyKitten',
    'ds_lily',
    'Elajjaz',
    'ESL_SC2',
    'Fairlight_Excalibur',
    'FollowGrubby',
    'GamesDoneQuick',
    'GernaderJake',
    'Giantwaffle',
    'GingiTV',
    'Gladd',
    'Glorious_E',
    'Grimmmz',
    'HyperRatTV',
    'IFrostBolt',
    'itmeJP',
    'JokerdTV',
    'JoshOG',
    'Klean',
    'limit_maximum',
    'LIRIK',
    'LVNDMARK',
    'Maximilian_DOOD',
    'Naguura',
    'Naowh',
    'nl_Kripp',
    'notmes',
    'nugiyen',
    'P4wnyhof',
    'Pestily',
    'Preachlfw',
    'PsheroTV',
    'Quin69',
    'RayNarvaezJr',
    'RetroGaijin',
    'richwcampbell',
    'Sacriel',
    'Sequisha',
    'Smashley',
    'Snowmixy',
    'SourSweet',
    'SovietWomble',
    'Steelmage',
    'StreamerHouse',
    'Strippin',
    'Sweatcicle',
    'T90Official',
    'TheRunningManZ',
    'Towelliee',
    'venruki',
    'Yogscast',
    'zackrawrr',
    'ZeplaHQ',
    'Zizaran',
]

[yellow]
algo = 'color'
max = 60
creators = [
    'AnniTheDuck',
    'AyeZee',
    'BastiGHG',
    'BeamTwitch',
    'chefstrobel',
    'ClassyBeef',
    'Dekarldent',
    'DerHauge',
    'Dhalucard',
    'DoktorFroid',
    'edopeh',
    'eliasn97',
    'ELoTRiX',
    'GRONKH',
    'GronkhTV',
    'GTimeTV',
    'H0llyLP',
    'hc_diZee',
    'HoneyPuu',
    'iBlali',
    'INSCOPE21TV',
    'Kamikatze',
    'katoo',
    'KayzahR',
    'MasterTay',
    'maxim',
    'MckyTV',
    'metashi12',
    'MontanaBlack88',
    'Mouzakrobat',
    'orangemorange',
    'PietSmiet',
    'PokerStars247',
    'ProdigyDDK',
    'Repaz',
    'RevedTV',
    'rewinside',
    'Rezo',
    'Robnic',
    'RoyalPhunk',
    'Rumathra',
    'RvNxMango',
    'SchwabbelTown',
    'ShoXx__',
    'Sintica',
    'TheKller',
    'TheRealKnossi',
    'TrilluXe',
    'Trymacs',
    'trymacs',
    'unsympathisch_tv',
    'Vlesk',
]

[orange]
algo = 'color'
max = 80
creators = [
    'AdrianaChechik_',
    'akaNemsko',
    'Alinity',
    'Anna_Chess',
    'Arcadum',
    'artesianbuilds',
    'Atrioc',
    'bokoen',
    'BotezLive',
    'cashmeow',
    'Central_Committee',
    'Chess',
    'chess24',
    'chessbrah',
    'ClintStevens',
    'CodeMiko',
    'cyr',
    'dafran',
    'DarkViperAU',
    'DashDucks',
    'Destiny',
    'DuelLinksMeta',
    'EsfandTV',
    'EXBC',
    'Farfa',
    'FinaoLive',
    'forsen',
    'GMHikaru',
    'gsmVoiD',
    'HasanAbi',
    'heyimbee',
    'Hungrybox',
    'ibabyrainbow',
    'ItsSliker',
    'jakenbakeLIVE',
    'Jerma985',
    'Jinnytty',
    'JonZherka',
    'kennybeats',
    'Kitboga',
    'Lacari',
    'Limmy',
    'Linkus7',
    'ludwig',
    'm0xyy',
    'Macaiyla',
    'mang0',
    'Maya',
    'Meowko',
    'Mizkif',
    'moistcr1tikal',
    'Murda',
    'pokelawls',
    'PokemonChallenges',
    'QTCinderella',
    'RiffTrax',
    'robcdee',
    'roflgator',
    'RubberNinja',
    'sashagrey',
    'Scrapie',
    'Simply',
    'SmallAnt',
    'sodapoppin',
    'Stanz',
    'Sweet_Anita',
    'theRealShooKon3',
    'TheStockGuy',
    'TimTheTatman',
    'TommyKayLIVE',
    'Trainwreckstv',
    'Vargskelethor',
    'VGBootCamp',
    'willneff',
    'Wirtual',
    'xQcOW',
    'Yuggie_TV',
    'Zoil',
]

[giants]
algo = 'edge'
max = 40
creators = [
    'AdinRoss',
    'Amouranth',
    'bateson87',
    'Bugha',
    'CohhCarnage',
    'dapr',
    'Deadlyslob',
    'ElisabeteTV',
    'erobb221',
    'forsen',
    'HasanAbi',
    'iiTzTimmy',
    'JokerdTV',
    'JoshOG',
    'keanelol',
    'KingGeorge',
    'Kitboga',
    'LIRIK',
    'Loserfruit',
    'LuluLuvely',
    'Mongraal',
    'MontanaBlack88',
    'NICKMERCS',
    'Quin69',
    'ShahZaM',
    'shroud',
    'sneakylol',
    'Subroza',
    'Tfue',
    'Tommey',
    'TSM_ImperialHal',
    'Vercetti',
    'wagnificent',
    'woohankyung',
    'xQcOW',
    'Yassuo',
    'ZeratoR',
    'Zerkaa',
    'ZubatLEL',
]

[pink]
algo = 'color'
max = 50
creators = [
    'anny',
    'AriaSaki',
    'AsianGuyStream',
    'BrookeAB',
    'BTMC',
    'dakotaz',
    'dish',
    'DumbDog',
    'Enviosity',
    'fobm4ster',
    'fuslie',
    'ironmouse',
    'kkatamina',
    'KristoferYee',
    'lilypichu',
    'Momo',
    'nukomaro2020',
    'nyanners',
    'OkCode',
    'peterparkTV',
    'PotasticP',
    'projektmelody',
    'QuarterJade',
    'Razerninjas',
    'Sekapoko',
    'Shibuya_Kaho',
    'Silvervale',
    'sleepy',
    'SteveSuptic',
    'Sydeon',
    'Sykkuno',
    'TinaKitten',
    'tuonto',
    'veibae',
    'xChocoBars',
    'YDCB',
    'yvonnie',
    'Zentreya',
]